resources:
  repositories:
    - repository: builds
      type: github
      name: igordemjanov/azure-pipelines-build
      ref: 'refs/heads/master'
      endpoint: 'igordemjanov'

trigger:
  branches:
    include:
    - master
    - feature/*
    - bug/*

stages:

- stage: Build
  displayName: Build
  
  jobs:

  # Build Infrastructure
  - template: zip.yml@builds
    parameters:
      name: 'Build_Azure_Functions_Infrastructure'
      display_name: 'Build Infrastructure'
      pool:
        name: 'Hosted Windows 2019 with VS2019'
      project_title: 'Azure.Functions.DI.Infrastructure'
      artifact_name: 'Functions'